# Generated by Django 4.2.20 on 2025-05-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_note_options_note_edited_note_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.URLField(default='https://api.dicebear.com/7.x/bottts/svg'),
        ),
    ]
