# Generated by Django 4.2.20 on 2025-05-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_watchlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlistitem',
            name='imdb_rating',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
