# Generated by Django 4.2.20 on 2025-05-24 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='movie_imdb_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='movie_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
